"""

NORMALIZADOR DE INTERVENCIONES QUIRÚRGICAS  
 Proyecto Analítica Pabellón Quirúrgico


ARQUITECTURA:
  Capa 1 — Pre-limpieza    : elimina prefijos (PAD/LEF/ACHS/SAP) y sufijos
                             de lateralidad (DERECHO/IZQUIERDO/BILATERAL)
  Capa 2 — MINI_ALIAS_MAP  : sólo ~50 reglas para lo que fuzzy NO puede
                             resolver: acrónimos (RTU, PTC, STC), sinónimos
                             semánticamente muy distintos (HERNIA → HERNIOPLASTIA)
  Capa 3 — Fuzzy matching  : rapidfuzz.fuzz.token_sort_ratio contra la lista
                             canónica en JSON (100% configurable sin tocar código)
  Capa 4 — Fallback        : devuelve la cadena pre-limpiada como categoría
                             "Otros" — nunca pierde información


USO:
  from normalizador_fuzzy import NormalizadorIntervencion

  norm = NormalizadorIntervencion(threshold=80)
  resultado = norm.normalizar("MANGA GASTRICA ALERGICA AL LATEX")
  # → NormResult(canonical='MANGA GÁSTRICA', score=95.2, method='fuzzy')

  # Drop-in replacement para normalizar_intervencion() del ETL original:
  nombre_limpio = norm.normalizar_str("LEF RTU PROSTATICA")
  # → 'RESECCIÓN TRANSURETRAL (RTU)'

"""

import re
import json
import unicodedata
from pathlib import Path
from dataclasses import dataclass
from typing import Optional

try:
    from rapidfuzz import fuzz, process as rf_process
    _RAPIDFUZZ = True
except ImportError:
    import difflib
    _RAPIDFUZZ = False



# CONFIGURACIÓN DE RUTAS

CANONICAL_JSON = Path(__file__).resolve().parent / "canonical_interventions.json"


MINI_ALIAS_MAP: dict[str, str] = {
    # Acrónimos ortopédicos 
    "PTC": "PRÓTESIS TOTAL DE CADERA (PTC)",
    "PTR": "PRÓTESIS TOTAL DE RODILLA (PTR)",
    "PTC DER": "PRÓTESIS TOTAL DE CADERA (PTC)",
    "PTC IZQ": "PRÓTESIS TOTAL DE CADERA (PTC)",
    "PTR DER": "PRÓTESIS TOTAL DE RODILLA (PTR)",
    "PTR IZQ": "PRÓTESIS TOTAL DE RODILLA (PTR)",
    "(SAP) PTR": "PRÓTESIS TOTAL DE RODILLA (PTR)",
    "(SAP) PTC": "PRÓTESIS TOTAL DE CADERA (PTC)",
    "LCA": "RECONSTRUCCIÓN DE LCA",
    "OTS": "RETIRO DE MATERIAL DE OSTEOSÍNTESIS",
    "RETIRO OTS": "RETIRO DE MATERIAL DE OSTEOSÍNTESIS",
    "RAFI": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "MBA": "ARTROSCOPIA DE RODILLA",
    "HNP": "RESECCIÓN HNP LUMBAR",
    # Acrónimos urológicos 
    "RTU": "RESECCIÓN TRANSURETRAL (RTU)",
    "RTU PROSTATA": "RESECCIÓN TRANSURETRAL (RTU)",
    "RTU PROSTATICA": "RESECCIÓN TRANSURETRAL (RTU)",
    "RTU VESICAL": "RESECCIÓN TRANSURETRAL (RTU)",
    "RTU DE PROSTATA": "RESECCIÓN TRANSURETRAL (RTU)",
    "HOLEP": "ENUCLEACIÓN PROSTÁTICA CON LÁSER (HOLEP)",
    "ADSP": "ADENOMECTOMÍA SUPRAPÚBICA",
    # Acrónimos médicos generales 
    "STC": "SÍNDROME DEL TÚNEL CARPIANO",
    "CPRE": "COLANGIOPANCREATOGRAFÍA (CPRE)",
    "CVC": "INSERCIÓN DE CATÉTER VENOSO CENTRAL",
    "TVT": "CINTA VAGINAL SIN TENSIÓN (TVT)",
    "TOT": "CINTA OBTURADORA TRANSOBTURADORA (TOT)",
    # Sinónimos semánticos (fuzzy score <70) 
    "HERNIA INGUINAL": "HERNIOPLASTIA INGUINAL",
    "HERNIA UMBILICAL": "HERNIOPLASTIA UMBILICAL",
    "HERNIA INCISIONAL": "HERNIOPLASTIA INCISIONAL",
    "HERNIA HIATAL": "HERNIOPLASTIA HIATAL",
    "HERNIA": "HERNIOPLASTIA",
    "FIMOSIS": "CIRCUNCISIÓN",
    "VARICOCELE": "VARICOCELECTOMÍA",
    "SINEQUIA NASAL": "RESECCIÓN DE SINEQUIA NASAL",
    "LUMBAR": "RESECCIÓN HNP LUMBAR",
    "RAQUIESTENOSIS": "DESCOMPRESIÓN LUMBAR",
    "REPA": "REPARACIÓN DE EVENTRACIÓN",
    "DRENAJE HEMATOMA": "DRENAJE DE ABSCESO",
    "RETINACULOTOMIA": "LIBERACIÓN DEL TÚNEL CARPIANO",
    "RETINACULOTOMÍA": "LIBERACIÓN DEL TÚNEL CARPIANO",
    "RADIOFRECUENCIA": "RIZOTOMÍA POR RADIOFRECUENCIA",
    "INESTABILIDAD RODILLA": "INESTABILIDAD DE RODILLA",
    "INESTABILIDAD HOMBRO": "INESTABILIDAD DE HOMBRO",
    "MANGUITO ROTADOR": "REPARACIÓN DE MANGUITO ROTADOR",
    "AUMENTO MAMARIO": "AUMENTO MAMARIO",
    "FX DE CADERA": "REDUCCIÓN DE FRACTURA DE CADERA",
    "FX CADERA": "REDUCCIÓN DE FRACTURA DE CADERA",
    "FX PELVIS": "REDUCCIÓN Y OSTEOSÍNTESIS",
    # Sinónimos de artroscopia (prefijo limpio a canónico) 
    "ARTROSCOPIA RODILLA": "ARTROSCOPIA DE RODILLA",
    "ARTROSCOPIA HOMBRO": "ARTROSCOPIA DE HOMBRO",
    "ARTROSCOPIA TOBILLO": "ARTROSCOPIA DE TOBILLO",
    "ARTROSCOPIA CODO": "ARTROSCOPIA DE CODO",
    "MENISECTOMIA RODILLA": "MENISCECTOMÍA DE RODILLA",
    "MENISCECTOMIA PARCIAL RODILLA": "MENISCECTOMÍA DE RODILLA",
    "MENISCECTOMÍA PARCIAL RODILLA": "MENISCECTOMÍA DE RODILLA",
    # BYPASS (con calificadores que confunden fuzzy) 
    "BYPASS GASTRICO":              "BYPASS",
    "BYPASS GÁSTRICO":              "BYPASS",
    # Artroscopias con lateralidad embebida 
    "ARTROSCOPIA RODILLA IZQ":      "ARTROSCOPIA DE RODILLA",
    "ARTROSCOPIA ROD":              "ARTROSCOPIA DE RODILLA",
    "ARTROCOPIA RODILLA":           "ARTROSCOPIA DE RODILLA",  # typo
    "ATROSCOPIA RODILLA":           "ARTROSCOPIA DE RODILLA",  # typo
    # Procedimientos con abreviaciones OTS/RAFI embebidas
    "RETIRO OTS + AQ":              "RETIRO DE MATERIAL DE OSTEOSÍNTESIS",
    "RED + OTS":                    "REDUCCIÓN Y OSTEOSÍNTESIS",
    "RAFI + TORNILLOS":             "REDUCCIÓN Y OSTEOSÍNTESIS",
    # Nuevos del Excel — PTC/PTR con lateralidad embebida 
    "PTC IZQUIERDA": "PRÓTESIS TOTAL DE CADERA (PTC)",
    "PTC IZQUIERDO": "PRÓTESIS TOTAL DE CADERA (PTC)",
    "PTC DERECHA": "PRÓTESIS TOTAL DE CADERA (PTC)",
    "PTR IZQUIERDA": "PRÓTESIS TOTAL DE RODILLA (PTR)",
    "PTR DERECHA": "PRÓTESIS TOTAL DE RODILLA (PTR)",
    "PROTESIS DE RODILLA": "PRÓTESIS TOTAL DE RODILLA (PTR)",
    "ENDOPROTESIS DE RODILLA": "PRÓTESIS TOTAL DE RODILLA (PTR)",
    "MANGA GASTRICA ALERGICA AL LATEX": "MANGA GÁSTRICA",
    "MANGA GÁSTRICA ALERGICA AL LATEX": "MANGA GÁSTRICA",
    "BYPASS ALERGICA AL LATEX": "BYPASS",
    "COLELITIASIS VLP": "COLECISTECTOMÍA VLP",
    "COLELITIASIS": "COLECISTECTOMÍA",
    "FISTULA ANAL": "FÍSTULA ANAL",
    "FISURA ANAL": "FISURA ANAL",
    "HEMORROIDECTOMIA": "HEMORROIDECTOMÍA",
    "HEMORROIDECTOMÍA": "HEMORROIDECTOMÍA",
    "QUISTE PILONIDAL": "RESECCIÓN DE QUISTE PILONIDAL",
    "RESECCION QUISTE PILONIDAL": "RESECCIÓN DE QUISTE PILONIDAL",
    "DILATACION URETRAL": "DILATACIÓN URETRAL",
    "DILATACIÓN URETRAL": "DILATACIÓN URETRAL",
    "URETROCISTOSCOPIA": "CISTOSCOPIA",
    "SUTURA MENISCAL RODILLA": "MENISCECTOMÍA DE RODILLA",
    "SUTURA MENISCO INTERNO RODILLA": "MENISCECTOMÍA DE RODILLA",
    "DEDO EN GATILLO": "APERTURA DE POLEA",
    "APERTURA POLEA": "APERTURA DE POLEA",
    "QUISTE SINOVIAL": "RESECCIÓN DE QUISTE SINOVIAL",
    "SAFENECTOMIA PIERNA": "SAFENECTOMÍA",
    "STC IZQ": "SÍNDROME DEL TÚNEL CARPIANO",
    "RINOSEPTOPLASTIA PRIMARIA": "RINOSEPTOPLASTIA",
    "REVISAR ENDOSCÓPICA EPISTAXIS": "EPISTAXIS",
    "LIO OD": "FACOEMULSIFICACIÓN + LIO",
    "LIO OI": "FACOEMULSIFICACIÓN + LIO",
    "BLOQUEO FACETARIO": "BLOQUEO FACETARIO",
    "BLOQUEO SACROILIACO": "BLOQUEO SACROILIACO",
    "REDUCCIÓN MAMARIA": "MAMOPLASTIA DE REDUCCIÓN",
    "REDUCCION MAMARIA": "MAMOPLASTIA DE REDUCCIÓN",
    "ABDOMINOPLASTIA CON LIPOSUCCION MENOR": "ABDOMINOPLASTIA",
    "LIPOABDOMINOPLASTIA CON TRANSFERENCIA GLUTEA": "LIPOABDOMINOPLASTIA",
    "LIPOABDOMINOPLASTIA VASER + IGG": "LIPOABDOMINOPLASTIA COMPLEJA (VASER/IGG)",
    "LIPOABDOMINOPLASTIA VASER IGG": "LIPOABDOMINOPLASTIA COMPLEJA (VASER/IGG)",
    "LIPOABDOMINOPLASTIA FULL TECH IGG": "LIPOABDOMINOPLASTIA COMPLEJA (VASER/IGG)",
    "LIPOABDOMINOPLASTIA FULL TECH + IGG": "LIPOABDOMINOPLASTIA COMPLEJA (VASER/IGG)",
    "LIPOABDOMINOPLASTIA VASER": "LIPOABDOMINOPLASTIA COMPLEJA (VASER/IGG)",
    "LIPOESCULTURA FULL TECH": "LIPOSUCCIÓN COMPLEJA (VASER/IGG)",
    "LIPO FULL TECH IGG": "LIPOSUCCIÓN COMPLEJA (VASER/IGG)",
    "LIPOSUCCION FULL TECH IGG": "LIPOSUCCIÓN COMPLEJA (VASER/IGG)",
    "LIPOVASER IGG": "LIPOSUCCIÓN COMPLEJA (VASER/IGG)",
    "LIPOVASER + IGG": "LIPOSUCCIÓN COMPLEJA (VASER/IGG)",
    "IMPLANTE MAMARIO": "AUMENTO MAMARIO",
    "REPARACION MANGUITO ROTADOR": "REPARACIÓN DE MANGUITO ROTADOR",
    "REPARACIÓN MANGUITO ROTADOR": "REPARACIÓN DE MANGUITO ROTADOR",
    "FX DE CLAVICULA": "REDUCCIÓN DE FRACTURA DE CLAVÍCULA",
    "FX CLAVICULA": "REDUCCIÓN DE FRACTURA DE CLAVÍCULA",
    "HEMORROIDES": "HEMORROIDECTOMÍA",
    "RINOSEPTOPLASTIA C/COSTILLA": "RINOSEPTOPLASTIA",
    "CISTOSCOPIA PARA RETIRO DE PIGTAIL": "CISTOSCOPIA",
    "BYPASS ALERGIA LATEX": "BYPASS",
    "HERNIA INGUINAL DERECHA PAD": "HERNIOPLASTIA INGUINAL",
    "HERNIA PAD": "HERNIOPLASTIA",
    "HERNIA UMBILICAL CON MALLA RECIDIVADA": "HERNIOPLASTIA UMBILICAL",
    "INFILTRACION FACETARIA Y PERIDURAL": "BLOQUEO FACETARIO Y PERIDURAL",
    "SINEQUIA": "RESECCIÓN DE SINEQUIA NASAL",
    "INSTALACION CVC": "INSERCIÓN DE CATÉTER VENOSO CENTRAL",
    "ABSCESO ANAL": "DRENAJE DE ABSCESO",
    "TUMOR DE PARTES BLANDAS": "RESECCIÓN DE TUMOR DE PARED ABDOMINAL",
    "REDUCCION NASAL": "REDUCCIÓN DE FRACTURA NASAL",
    "RECONTRUCCION LIGAMENTO CRUZADO ANTERIOR Y SUTURA MENISCAL": "RECONSTRUCCIÓN DE LCA + MENISCORRAFIA",
    "RECONSTRUCCION LCA RODILLA MAS MENISCECTOMIA": "RECONSTRUCCIÓN DE LCA + MENISCORRAFIA",
    "RECONSTRUCCIÓN LCA + MENISCO": "RECONSTRUCCIÓN DE LCA + MENISCORRAFIA",
    "FX DE TOBILLO DERECHO - RAFI": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "FX DE CADERA - REDUCCION + OTS": "REDUCCIÓN DE FRACTURA DE CADERA",
    "FX EDR DERECHA - RED + OTS": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "STC DERECHO SEVERO": "SÍNDROME DEL TÚNEL CARPIANO",
    "RESECCION HNP C6C7": "HNP CERVICAL - RESECCIÓN",
    "FIMOSIS CIRCUNSICION": "CIRCUNCISIÓN",
    "ESTABILIZACION LUMBAR": "ARTRODESIS LUMBAR",
    "CERVICAL 1 ESPACIO": "HNP CERVICAL",
    "HISTERECTOMÍA TOTAL + ANEXECTOMÍA BILATERAL LAPAROSCÓPICA": "HISTERECTOMÍA TOTAL LAPAROSCÓPICA",
    "SINDROME DE TUNEL CARPIANO- RETINACULOTOMIA": "SÍNDROME DEL TÚNEL CARPIANO",
    "TVT + CISTOSCOPIA - INCONTINENCIA URINARIA": "CINTA VAGINAL SIN TENSIÓN (TVT)",
    "URETEROSCOPIA + INSTALACIÓN DE PIGTAIL": "URETEROSCOPIA + STENT",
    "URETEROSCOPIA DERECHA + INSTALACIÓN DE PIGTAIL": "URETEROSCOPIA + STENT",
    "VARICOCELECTOMIA MICROQUIRÚRGICA": "VARICOCELECTOMÍA",
    "RADIOFRECUENCIA GANGLIO IMPAR": "RADIOFRECUENCIA DE GANGLIO IMPAR",
    "REDUCCION LIGAMENTO CRUZADO ANTERIOR Y SUTURA MENSICAL": "RECONSTRUCCIÓN DE LCA + MENISCORRAFIA",
    "RECONSTRUCCION LIGAMENTO CRUZADO ANTERIOR + SUTURA MENISCAL": "RECONSTRUCCIÓN DE LCA + MENISCORRAFIA",
    "RECONSTRUCCIÓN LCA Y SUTURA MENISCO EXTERNO": "RECONSTRUCCIÓN DE LCA + MENISCORRAFIA",
    "RECONSTRUCCIÓN LCA Y SUTURA MENISCO INTERNO": "RECONSTRUCCIÓN DE LCA + MENISCORRAFIA",
    "RECONSTRUCCIÓN LIGAMENTO CRUZADO ANTERIOR Y SUTURA MENISCO INTERNO": "RECONSTRUCCIÓN DE LCA + MENISCORRAFIA",
    "RECONSRUCCION LCA RODILLA": "RECONSTRUCCIÓN DE LCA",
    "HIPERTROFIA MAMARIA, MAMOPLASTIA DE REDUCCION": "MAMOPLASTIA DE REDUCCIÓN",
    "PLASTIA+ HISTEROPEXIA + FIJACION SACROESPINOSO + PERINEOPLASTIA": "SACROCOLOPEXIA + PERINEOPLASTIA",
    "RETIRO DE CATÉTER QX": "RETIRO DE CATÉTER",
    "SAFENECTOMIA UNILATERAL": "SAFENECTOMÍA",
    "FRACTURA RADIO Y CUBITO DISTAL": "REDUCCIÓN DE FRACTURA DE RADIO Y CÚBITO",
    "TENORRAFIA DE AQUILES": "TENORRAFIA DE AQUILES",
    "TENORRAFIA PERCUTANEA TENDON AQUILES": "TENORRAFIA DE AQUILES",
    "TENORRAFIA PERCUTÁNEA DE AQUILES": "TENORRAFIA DE AQUILES",
    "REPARACION DE AQUILES": "TENORRAFIA DE AQUILES",
    "REPARACION AQUILES": "TENORRAFIA DE AQUILES",
    "ROTURA DE AQUILES": "TENORRAFIA DE AQUILES",
    "ROTURA TENDON DE AQUILES": "TENORRAFIA DE AQUILES",
    "TENDON AQUILES": "TENORRAFIA DE AQUILES",
    "TENDÓN DE AQUILES": "TENORRAFIA DE AQUILES",
    "ROTURA AGUDA TENDON AQUILES": "TENORRAFIA DE AQUILES",
    "ROTURA SUBAGUDA TENDON AQUILES": "TENORRAFIA DE AQUILES",
    "TENORRAFIA ABIERTA AQUILES": "TENORRAFIA DE AQUILES",
    "PIE PLANO ARTRODESIS TRIPLE": "ARTRODESIS TRIPLE DE PIE",
    "ARTRODESIS TRIPLE": "ARTRODESIS TRIPLE DE PIE",
    "ARTRODESIS SUBTALAR": "ARTRODESIS TRIPLE DE PIE",
    "ARTRODESIS IF PULGAR": "ARTRODESIS",
    "ARTRODESIS MUÑECA": "ARTRODESIS DE MUÑECA",
    "ARTROSIS MUÑECA ARTRODESIS": "ARTRODESIS DE MUÑECA",
    "ARTRODESIS INESTABILIDAD": "ARTRODESIS",
    "ARTRODESIS C6 C7": "ARTRODESIS",
    "INESTABILIDAD TOBILLO ARTROSCOPIA": "ARTROSCOPIA DE TOBILLO",
    "INESTABILIDAD TOBILLO BROSTROM": "ARTROSCOPIA DE TOBILLO",
    "BROSTROM ARTROSCOPICO": "ARTROSCOPIA DE TOBILLO",
    "BROSTROM ARTROSCÓPICO": "ARTROSCOPIA DE TOBILLO",
    "INESTABILIDAD DE TOBILLO ARTROSCOPIA": "ARTROSCOPIA DE TOBILLO",
    "HALLUX VALGUS BILATERAL OSTEOTOMIA": "HALLUX VALGUS",
    "HALLUX VALGUS BILATERAL ARTRODESIS": "HALLUX VALGUS",
    "HALLUX VALGUS GARRA OSTEOTOMIA": "HALLUX VALGUS",
    "HALLUX RIGIDUS ARTRODESIS": "HALLUX VALGUS",
    "GARRA DEDO OSTEOTOMIA": "OSTEOTOMÍA",
    "GARRA SINTOMATICA OSTEOTOMIA": "OSTEOTOMÍA",
    "DEFORMIDADES ADQUIRIDAS DEDOS PIE": "OSTEOTOMÍA",
    "TRANSLOCACION TENDINOSA TOBILLO": "ARTRODESIS DE TOBILLO",
    "PIE CAVO RETIRO VIGA": "RETIRO DE MATERIAL DE OSTEOSÍNTESIS",
    "RECONTRUCCION LIGAMENTO CRUZADO ANTERIOR": "RECONSTRUCCIÓN DE LCA",
    "RECONSTRUCCION LIGAMENTO CRUZADO ANTERIOR": "RECONSTRUCCIÓN DE LCA",
    "RECONSTRUCCIÓN DE LIGAMENTO CRUZADO ANTERIOR": "RECONSTRUCCIÓN DE LCA",
    "RECONSTRUCCION LIGAMIENTO CRUZADO ANTERIOR": "RECONSTRUCCIÓN DE LCA",
    "RECONSTRUCCION LCA": "RECONSTRUCCIÓN DE LCA",
    "RECONSTRUCCIÓN LCA": "RECONSTRUCCIÓN DE LCA",
    "LIGAMENTO CRUZADO ANTERIOR": "RECONSTRUCCIÓN DE LCA",
    "LCA RODILLA": "RECONSTRUCCIÓN DE LCA",
    "LCA MENISCO": "RECONSTRUCCIÓN DE LCA + MENISCORRAFIA",
    "LCA SUTURA MENISCAL": "RECONSTRUCCIÓN DE LCA + MENISCORRAFIA",
    "RECONSTRUCCION LCA MENISCECTOMIA": "RECONSTRUCCIÓN DE LCA + MENISCORRAFIA",
    "RECONSTRUCCIÓN LCA MENISCO": "RECONSTRUCCIÓN DE LCA + MENISCORRAFIA",
    "RECONSTRUCCION LCA MENISCO": "RECONSTRUCCIÓN DE LCA + MENISCORRAFIA",
    "RECONTRUCCION LCA MENISCO": "RECONSTRUCCIÓN DE LCA + MENISCORRAFIA",
    "RECONSTRUCCIÓN LCA SUTURA MENISCAL": "RECONSTRUCCIÓN DE LCA + MENISCORRAFIA",
    "RECONSTRUCCION LIGAMENTO CRUZADO ANTERIOR SUTURA MENISCAL": "RECONSTRUCCIÓN DE LCA + MENISCORRAFIA",
    "ROTURA LCA SUTURA MENISCAL": "RECONSTRUCCIÓN DE LCA + MENISCORRAFIA",
    "REPARARACION LCA SUTURA MENISCAL": "RECONSTRUCCIÓN DE LCA + MENISCORRAFIA",
    "REINSERCION RAIZ POSTERIOR MENISCO": "RECONSTRUCCIÓN DE LCA + MENISCORRAFIA",
    "RECONSTRUCCIÓN LIGAMENTO CUADRICIPITAL": "RECONSTRUCCIÓN LIGAMENTO CUADRICIPITAL",
    "RECONSTRUCCIÓN LIGAMENTO PATELOFEMORAL": "RECONSTRUCCIÓN INESTABILIDAD PATELOFEMORAL",
    "RECONSTRUCCION INESTABILIDAD PATELOFEMORAL": "RECONSTRUCCIÓN INESTABILIDAD PATELOFEMORAL",
    "OSTEOTOMIA DE FULKERSON": "RECONSTRUCCIÓN INESTABILIDAD PATELOFEMORAL",
    "INESTABILIDAD SUTURA MENISCAL": "RECONSTRUCCIÓN DE LCA + MENISCORRAFIA",
    "INESTABILIDAD CON SUTURA": "RECONSTRUCCIÓN DE LCA + MENISCORRAFIA",
    "INESTABILIDAD DE RODILLA SUTURA MENISCAL": "RECONSTRUCCIÓN DE LCA + MENISCORRAFIA",
    "ROTURA LCA": "RECONSTRUCCIÓN DE LCA",
    "SUTURA MENISCAL": "MENISCECTOMÍA DE RODILLA",
    "MENISCO RODILLA": "MENISCECTOMÍA DE RODILLA",
    "ARTROSCOPIA MENISCAL": "ARTROSCOPIA DE RODILLA",
    "ARTROSCOPIA RODILLA SUTURA MENISCAL": "ARTROSCOPIA DE RODILLA",
    "MENISECTOMIA": "MENISCECTOMÍA DE RODILLA",
    "ARTROSCOPIA PAD": "ARTROSCOPIA DE RODILLA",
    "MANGUITO ROTADOR HOMBRO": "REPARACIÓN DE MANGUITO ROTADOR",
    "REPARACION SUPRAESPINOSO": "REPARACIÓN DE MANGUITO ROTADOR",
    "SINDROME DEL MANGUITO ROTADOR": "REPARACIÓN DE MANGUITO ROTADOR",
    "REPARACION HOMBRO": "REPARACIÓN DE MANGUITO ROTADOR",
    "PROTESIS DE HOMBRO": "ARTROPLASTIA DE HOMBRO",
    "ARTROPLASTIA HOMBRO": "ARTROPLASTIA DE HOMBRO",
    "FX EDR": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "FRACTURA EDR": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "FX RADIO DISTAL": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "FRACTURA RADIO DISTAL": "REDUCCIÓN DE FRACTURA DE RADIO Y CÚBITO",
    "FX RADIO CUBITO DISTAL": "REDUCCIÓN DE FRACTURA DE RADIO Y CÚBITO",
    "FRACTURA RADIO CUBITO DISTAL": "REDUCCIÓN DE FRACTURA DE RADIO Y CÚBITO",
    "FX DE MUÑECA": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "FRACTURA MUÑECA": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "FX MUÑECA": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "FRACTURA ANTEBRAZO": "REDUCCIÓN DE FRACTURA DE RADIO Y CÚBITO",
    "FX ANTEBRAZO": "REDUCCIÓN DE FRACTURA DE RADIO Y CÚBITO",
    "FRACTURA CUBITO": "REDUCCIÓN DE FRACTURA DE RADIO Y CÚBITO",
    "FX OLECRANON": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "FX OLÉCRANON": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "FX CUPULA RADIAL": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "FX PLATILLO TIBIAL": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "FRACTURA PLATILLO TIBIAL": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "FX PIERNA": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "FRACTURA PIERNA": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "FX FEMUR": "OSTEOSÍNTESIS CON CLAVO GAMMA",
    "FRACTURA FEMUR": "OSTEOSÍNTESIS CON CLAVO GAMMA",
    "FRACTURA SUBTROCANTERICA": "OSTEOSÍNTESIS CON CLAVO GAMMA",
    "CEM FEMUR": "OSTEOSÍNTESIS CON CLAVO GAMMA",
    "FX ROTULA": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "FRACTURA ROTULA": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "FX ESCAFOIDES": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "FRACTURA ESCAFOIDES": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "FX PELVIS": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "FRACTURA PELVIS": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "FRACTURA HUMERO": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "FX HUMERO": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "LUXACION HOMBRO FRACTURA HUMERO": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "LUXOFRACTURA TOBILLO RAFI": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "LUXOFRACTURA BIMALEOLAR": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "LUXOFRACTURA TRIMALEOLAR": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "LUXOFRACTURA LISFRANC": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "LUXOFRACTURA CODO": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "LUXOFRACTURA HOMBRO": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "LUXO FX TOBILLO": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "FRACTURA TOBILLO": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "FX TOBILLO": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "FX TOBILLO RAFI": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "FX DE TOBILLO": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "FX BASE 5 METATARSIANO": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "FX 5 METACARPIANO": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "FRACTURA METACARPIANO": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "FX F1 MEÑIQUE": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "FX F1 ANULAR": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "FRACTURA F1": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "FRACTURA MANDIBULAR": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "FRACTURAS MULTIPLES FEMUR": "REDUCCIÓN Y OSTEOSÍNTESIS",
    "RETIRO OTS SINTOMATICAS": "RETIRO DE MATERIAL DE OSTEOSÍNTESIS",
    "RETIRO DE TORNILLOS OTS": "RETIRO DE MATERIAL DE OSTEOSÍNTESIS",
    "RETIRO PLACA": "RETIRO DE MATERIAL DE OSTEOSÍNTESIS",
    "RETIRO DE PLACA": "RETIRO DE MATERIAL DE OSTEOSÍNTESIS",
    "RETIRO FIJADOR EXTERNO": "RETIRO DE MATERIAL DE OSTEOSÍNTESIS",
    "RETIRO DE FIJADOR EXTERNO": "RETIRO DE MATERIAL DE OSTEOSÍNTESIS",
    "MIGRACIÓN DE OTS": "RETIRO DE MATERIAL DE OSTEOSÍNTESIS",
    "MIGRACIÓN OTS": "RETIRO DE MATERIAL DE OSTEOSÍNTESIS",
    "RETIRO TORNILLO": "RETIRO DE MATERIAL DE OSTEOSÍNTESIS",
    "RETIRO DE TORNILLO": "RETIRO DE MATERIAL DE OSTEOSÍNTESIS",
    "OSTEOSINTESIS SINTOMATICA": "RETIRO DE MATERIAL DE OSTEOSÍNTESIS",
    "OSTEOSÍNTESIS SINTOMÁTICA": "RETIRO DE MATERIAL DE OSTEOSÍNTESIS",
    "ESCARECTOMIA PLASTIA": "ESCARECTOMÍA + CIERRE",
    "ESCARECTOMIA CIERRE": "ESCARECTOMÍA + CIERRE",
    "ESCARECTOMIA INJERTO PIEL": "ESCARECTOMÍA + INJERTO DE PIEL",
    "HERIDA COMPLICADA ESCARECTOMIA": "ESCARECTOMÍA + CIERRE",
    "HERIDA COMPLEJA COLGAJO": "ESCARECTOMÍA + CIERRE",
    "ASEO QUIRURGICO SUTURA": "ASEO QUIRÚRGICO",
    "ASEO QUIRURGICO VAC": "ASEO QUIRÚRGICO",
    "ASEO VAC": "ASEO QUIRÚRGICO",
    "CAMBIO DE VAC": "CAMBIO DE VAC",
    "RECAMBIO DE VAC": "CAMBIO DE VAC",
    "UCI CAMBIO DE VAC": "CAMBIO DE VAC",
    "DEHISCENCIA HERIDA OPERATORIA": "REVISIÓN HERIDA OPERATORIA",
    "BOCIO NODULAR LOBECTOMIA": "LOBECTOMÍA TIROIDEA",
    "BOCIO NODULAR LOBECTOMÍA": "LOBECTOMÍA TIROIDEA",
    "LOBECTOMIA TIROIDEA": "LOBECTOMÍA TIROIDEA",
    "BOCIO CANCER TIROIDES": "TIROIDECTOMÍA",
    "HIPERPARATIROIDISMO PARATIROIDECTOMIA": "TIROIDECTOMÍA",
    "MELANOMA RESECCION BIOPSIA": "MELANOMA - RESECCIÓN + BIOPSIA LINFONODO",
    "MELANOMA AMPLIACION MARGENES": "MELANOMA - RESECCIÓN + BIOPSIA LINFONODO",
    "MELANOMA BIOPSIA LINFONODO": "MELANOMA - RESECCIÓN + BIOPSIA LINFONODO",
    "SARCOMA RESECCION": "RESECCIÓN DE TUMOR DE PARTES BLANDAS",
    "RESECCION TUMOR PARTES BLANDAS": "RESECCIÓN DE TUMOR DE PARTES BLANDAS",
    "RESECCIÓN TUMOR DE PARTES BLANDAS": "RESECCIÓN DE TUMOR DE PARTES BLANDAS",
    "TU PARTES BLANDAS": "RESECCIÓN DE TUMOR DE PARTES BLANDAS",
    "RESECCION TU ESCAPULAR": "RESECCIÓN DE TUMOR DE PARTES BLANDAS",
    "RESECCION LIPOMA": "RESECCIÓN DE LIPOMA",
    "LIPOMA EXTIRPACION": "RESECCIÓN DE LIPOMA",
    "LIPOMA RESECCION": "RESECCIÓN DE LIPOMA",
    "LIPOMA DORSAL": "RESECCIÓN DE LIPOMA",
    "NODULO MAMA BIOPSIA": "MASTECTOMÍA PARCIAL",
    "CANCER DE MAMA MASTECTOMIA PARCIAL": "MASTECTOMÍA PARCIAL",
    "CA MAMA MASTECTOMIA PARCIAL": "MASTECTOMÍA PARCIAL",
    "FIJACION ARTRODESIS LUMBAR": "ARTRODESIS LUMBAR",
    "FIJACION LUMBAR DESCOMPRESIVA": "ARTRODESIS LUMBAR",
    "ESPONDILOLISTESIS ARTRODESIS": "ARTRODESIS LUMBAR",
    "LAMINECTOMIA DISCECTOMIA FIJACION": "ARTRODESIS LUMBAR",
    "FRACTURA LUMBAR ARTRODESIS": "ARTRODESIS LUMBAR",
    "FIJACION PERCUTANEA FRACTURA VERTEBRAL": "FIJACIÓN PERCUTÁNEA",
    "MICRODISCECTOMIA LUMBAR": "RESECCIÓN HNP LUMBAR",
    "DISECTOMIA HNP LUMBAR": "RESECCIÓN HNP LUMBAR",
    "DISCECTOMIA LUMBAR": "RESECCIÓN HNP LUMBAR",
    "HNP LUMBAR L4 L5": "RESECCIÓN HNP LUMBAR",
    "HNP LUMBARL4 L5": "RESECCIÓN HNP LUMBAR",
    "RESECCION HNP L4 L5": "RESECCIÓN HNP LUMBAR",
    "RESECCION HNP LUMBAR L2 L3": "RESECCIÓN HNP LUMBAR",
    "RESECCION HNP L5 S1": "RESECCIÓN HNP LUMBAR",
    "ESTENOSIS FORAMINAL": "DESCOMPRESIÓN LUMBAR",
    "EXCERESIS MICROQX HNP": "RESECCIÓN HNP LUMBAR",
    "HNP CERVICAL": "RESECCIÓN HNP LUMBAR",
    "HNP C4 C5": "RESECCIÓN HNP LUMBAR",
    "RESECCION HNP CERVICAL": "RESECCIÓN HNP LUMBAR",
    "RESECCION CERVICAL C6 C7": "RESECCIÓN HNP LUMBAR",
    "RESECCION HNP C5 C6 CAGE": "RESECCIÓN HNP LUMBAR",
    "INESTABILIDAD ARTRODESIS C6 C7": "ARTRODESIS",
    "CHIARI I": "DESCOMPRESIÓN LUMBAR",
    "VALVULA DERIVATIVA VP": "VÁLVULA DERIVATIVA VENTRICULOPERITONEAL",
    "VALVULA DERIVATIVA V-P": "VÁLVULA DERIVATIVA VENTRICULOPERITONEAL",
    "NEUROESTIMULADOR MEDULAR": "NEUROESTIMULADOR MEDULAR",
    "REPOSICION GENERADOR NEUROESTIMULADOR": "NEUROESTIMULADOR MEDULAR",
    "BIOPSIA VERTEBRA": "BIOPSIA DE VÉRTEBRA",
    "BIOPSIA DE VERTEBRA": "BIOPSIA DE VÉRTEBRA",
    "ARTROLISIS DEDO": "ARTROLISIS ARTROSCÓPICA",
    "TENOLISIS FLEXORES": "ARTROLISIS ARTROSCÓPICA",
    "ARTROLISIS ARTROSCOPICA": "ARTROLISIS ARTROSCÓPICA",
    "ARTROLISIS ARTROSCÓPICA": "ARTROLISIS ARTROSCÓPICA",
    "LIBERACION ARTROSCOPICA SINOVECTOMIA": "ARTROLISIS ARTROSCÓPICA",
    "DEDO EN GATILLO PULGAR": "APERTURA DE POLEA",
    "POLEA A1 DEDO MEDIO": "APERTURA DE POLEA",
    "STC LIBERACION POLEA": "LIBERACIÓN DEL TÚNEL CARPIANO",
    "STC NEURITIS CUBITAL": "LIBERACIÓN DEL TÚNEL CARPIANO",
    "TRASLOCACION NERVIO CUBITAL": "LIBERACIÓN DEL TÚNEL CARPIANO",
    "RETINACULOTOMIA PAD": "LIBERACIÓN DEL TÚNEL CARPIANO",
    "NEUROLISIS MEDIANO": "LIBERACIÓN DEL TÚNEL CARPIANO",
    "MALLET FINGER": "ASEO QUIRÚRGICO",
    "DUPUYTREN MANO": "FASCIOTOMÍA POR ENFERMEDAD DE DUPUYTREN",
    "LESION STENER": "ASEO QUIRÚRGICO",
    "LESION EXTENSOR TENORRAFIA": "NEURORRAFIA",
    "SECCION FLEXOR TENORRAFIA": "NEURORRAFIA",
    "TENORRAFIA": "NEURORRAFIA",
    "NEURORRAFIA": "NEURORRAFIA",
    "RESECCION NEUROMA": "RESECCIÓN DE NEUROMA",
    "NEURECTOMIA": "RESECCIÓN DE NEUROMA",
    "NEUROMA DEDO": "RESECCIÓN DE NEUROMA",
    "QUISTE GANGLION": "RESECCIÓN DE QUISTE SINOVIAL",
    "GANGLION EN MANO": "RESECCIÓN DE QUISTE SINOVIAL",
    "QUISTE SINOVIAL MUÑECA": "RESECCIÓN DE QUISTE SINOVIAL",
    "EXTIRPACION QUISTE": "RESECCIÓN DE QUISTE SINOVIAL",
    "COLECTOMIA TOTAL VLP": "COLECTOMÍA LAPAROSCÓPICA",
    "COLECTOMIA LAP": "COLECTOMÍA LAPAROSCÓPICA",
    "COLECTOMÍA CON DESCENSO COLON": "COLECTOMÍA LAPAROSCÓPICA",
    "DESCENSO COLON LAPAROSCOPICO": "COLECTOMÍA LAPAROSCÓPICA",
    "SIGMOIDES VLP": "SIGMOIDECTOMÍA",
    "SIGMOIDECTOMIA": "SIGMOIDECTOMÍA",
    "RESECCION ANTERIOR VLP RECTO": "SIGMOIDECTOMÍA",
    "COLOSTOMIA COLONOSCOPIA": "COLOSTOMÍA",
    "TAMIS": "CIRUGÍA TRANSANAL (TAMIS)",
    "RECONSTRUCCION DE TRANSITO": "RECONSTRUCCIÓN DE TRÁNSITO",
    "RECONSTRUCCIÓN DE TRÁNSITO": "RECONSTRUCCIÓN DE TRÁNSITO",
    "FISTULA ANAL RESECCION": "FÍSTULA ANAL",
    "HEMORROIDE CON STAPLER": "HEMORROIDECTOMÍA",
    "HEMORROIDES CON STAPLER": "HEMORROIDECTOMÍA",
    "HEMORROIDE": "HEMORROIDECTOMÍA",
    "RTU VESICAL DOXORRUBICINA": "RESECCIÓN TRANSURETRAL (RTU)",
    "RTUVESICAL": "RESECCIÓN TRANSURETRAL (RTU)",
    "TUMOR VESICAL RESECCION TRANSURETRAL": "RESECCIÓN TRANSURETRAL (RTU)",
    "LITOTRIPSIA EXTRA CORPOREA": "LITOTRIPSIA EXTRACORPÓREA",
    "LITOTRIPSIA": "LITOTRIPSIA EXTRACORPÓREA",
    "DRENAJE DE HIDRONEFROSIS": "DRENAJE DE HIDRONEFROSIS",
    "DRENAJE ENDOSCOPICO HIDRONEFROSIS": "DRENAJE DE HIDRONEFROSIS",
    "NEFRECTOMIA RADICAL VLP": "NEFRECTOMÍA RADICAL",
    "NEFRECTOMIA RADICAL": "NEFRECTOMÍA RADICAL",
    "ESPERMATOCELECTOMÍA": "ESPERMATOCELECTOMÍA",
    "ORQUIECTOMIA PROTESIS": "ORQUIECTOMÍA + PRÓTESIS",
    "ORQUIECTOMIA RADICAL": "ORQUIECTOMÍA RADICAL",
    "TU TESTICULAR ORQUIDECTOMIA": "ORQUIECTOMÍA RADICAL",
    "HISTERECTOMIA LAPAROSCOPICA": "HISTERECTOMÍA",
    "HISTERECTOMÍA LAPAROSCÓPICA": "HISTERECTOMÍA",
    "HISTERECTOMIA TOTAL LAPAROSCOPICA": "HISTERECTOMÍA",
    "QUISTECTOMIA LAPAROSCOPICA": "HISTEROSCOPIA",
    "PLASTIA HISTEROPEXIA FIJACION SACROESPINOSO": "SACROCOLOPEXIA",
    "HISTEROPEXIA FIJACION SACROESPINOSO": "SACROCOLOPEXIA",
    "PLASTIA POSTERIOR PERINEOPLASTIA": "SACROCOLOPEXIA + PERINEOPLASTIA",
    "PROLAPSO ANTERIOR CUPULA VAGINAL TOT": "CINTA OBTURADORA (TOT) + SACROCOLOPEXIA",
    "INCONTINENCIA URINARIA TOT": "CINTA OBTURADORA TRANSOBTURADORA (TOT)",
    "TVT CISTOSCOPIA": "CINTA VAGINAL SIN TENSIÓN (TVT)",
    "RINOSEPTOPLASTIA AURICULOPLASTIA": "RINOSEPTOPLASTIA",
    "RINOSEPTOPLASTIA TURBINECTOMÍA": "RINOSEPTOPLASTIA + TURBINECTOMÍA",
    "RINOSEPTOPLASTIA E DE CORNETES": "RINOSEPTOPLASTIA + TURBINECTOMÍA",
    "FARINGOPLASTIA SEPTOPLASTIA": "FARINGOPLASTIA",
    "SEPTOPLASTIA CAUTERIZACION CORNETES": "SEPTOPLASTIA + ECC",
    "REINTERVENCIÓN REDUCCION NASAL": "REDUCCIÓN NASAL",
    "ADENOAMIGDALECTOMIA PUNCION TIMPÁNICA": "ADENOAMIGDALECTOMÍA",
    "ADENOIDECTOMIA PUNCION TIMPÁNICA": "ADENOIDECTOMÍA + TIMPANOSTOMÍA",
    "PAD ADENOAMIGDALECTOMÍA REV VIA AEREA": "ADENOAMIGDALECTOMÍA",
    "AMIGDALECTOMIA PUNCION COLLERA": "AMIGDALECTOMÍA",
    "CIRUGÍA ANTIRREFLUJO CONVERSIÓN SANTORO": "CIRUGÍA ANTIRREFLUJO",
    "CIRUGIA ANTIREFLUJO COLECISTECTOMIA": "CIRUGÍA ANTIRREFLUJO",
    "REFLUJO": "CIRUGÍA ANTIRREFLUJO",
    "CONVERSION MANGA BYPASS": "CONVERSIÓN A BYPASS",
    "BYPASS PAD": "BYPASS",
    "PAS BYPASS": "BYPASS",
    "INSTALACION CATETER LINFOMA": "INSERCIÓN DE CATÉTER VENOSO CENTRAL",
    "INSTALACION DECATETER LINFOMA": "INSERCIÓN DE CATÉTER VENOSO CENTRAL",
    "RETIRO DE CATETER": "RETIRO DE CATÉTER",
    "RETIRO CATETER ONCOVIDA": "RETIRO DE CATÉTER",
    "RETIRO DE PIGTAIL": "CISTOSCOPIA",
    "EXPLORACION CATETER": "MANIPULACIÓN DE CATÉTER",
    "CISTOSCOPIA RETIRO PIGTAIL": "CISTOSCOPIA",
    "EXODONCIA ROG": "EXODONCIA + REGENERACIÓN ÓSEA",
    "EXODONCIA IMPLANTE": "IMPLANTE DENTAL",
    "FX RADICULAR IMPLANTE": "IMPLANTE DENTAL",
    "COLOCACION IMPLANTE DENTAL": "IMPLANTE DENTAL",
    "COLOCACION IMPLANTES": "IMPLANTE DENTAL",
    "IMPLANTE PIEZA": "IMPLANTE DENTAL",
    "ROG": "REGENERACIÓN ÓSEA GUIADA",
    "TAPP INGUINAL BILATERAL": "TAPP INGUINAL",
    "TAPP INGUINAL": "TAPP INGUINAL",
    "HERNIOPLASTIA COMPLEJA": "HERNIOPLASTIA VENTRAL",
    "HERNIOPLASTIA CENTRAL": "HERNIOPLASTIA UMBILICAL",
    "HERNIA INSICIONAL": "HERNIOPLASTIA INCISIONAL",
    "HERNIA INGUINAL BILATERAL LAP": "HERNIOPLASTIA INGUINAL BILATERAL LAPAROSCÓPICA",
    "HERNIA DE SPIEGEL": "HERNIOPLASTIA",
    "CIRUGÍA HERNIA ABDOMINAL": "HERNIOPLASTIA ABDOMINAL",
    "CUT OUT FX CADERA ARTROPLASTIA TOTAL": "ARTROPLASTIA TOTAL DE CADERA DE REVISIÓN",
    "CAEC NMV PTC": "PRÓTESIS TOTAL DE CADERA (PTC)",
    "SAP PTC DISPLASICA": "PRÓTESIS TOTAL DE CADERA (PTC)",
    "SAP PTC CONSALUD": "PRÓTESIS TOTAL DE CADERA (PTC)",
    "LEF REVISIÓN CADERA": "ARTROPLASTIA TOTAL DE CADERA DE REVISIÓN",
    "LEF RETIRO PROTESIS CADERA": "ARTROPLASTIA TOTAL DE CADERA DE REVISIÓN",
    "REVISION CADERA TIEMPO": "ARTROPLASTIA TOTAL DE CADERA DE REVISIÓN",
    "ARTROLISIS ARTROSCOPIA": "ARTROLISIS ARTROSCÓPICA",
    "LEF ARTROLISIS ARTROSCÓPICA": "ARTROLISIS ARTROSCÓPICA",
    "INFILTRACION FORAMINAL": "BLOQUEO FACETARIO",
    "BLOQUEO FACETARIO Y PERIDURAL": "BLOQUEO FACETARIO",
    "BLOQUEO GANGLIO IMPAR": "BLOQUEO DE GANGLIO IMPAR",
    "RADIOFRECUENCIA GANGLIO IMPAR": "RADIOFRECUENCIA DE GANGLIO IMPAR",
    "RADIOFRECUENCIA PULSADA": "RIZOTOMÍA POR RADIOFRECUENCIA",
    "LEF RIZOTOMÍA GENICULADOS": "RIZOTOMÍA POR RADIOFRECUENCIA",
    "RIZOTOMIA": "RIZOTOMÍA POR RADIOFRECUENCIA",
    "BLEFAROPLASTIA BLAFAROCHALASIS": "BLEFAROPLASTIA",
    "BLEFAROPLASTIA SUPERIOR INFERIOR": "BLEFAROPLASTIA",
    "CICATRIZ LOBULO AURICULAR": "RESECCIÓN DE CICATRIZ",
    "RESECCION PLASTICA CICATRIZ": "RESECCIÓN DE CICATRIZ",
    "CICATRIZ QUELOIDE": "RESECCIÓN DE CICATRIZ QUELOIDE",
    "MASTOPEXIA PERIAREOLAR IMPLANTE": "MASTOPEXIA CON IMPLANTES",
    "MASTOPEXIA PERIAREOLAR": "MASTOPEXIA CON IMPLANTES",
    "MINIABDOMINOPLASTIA": "MINIABDOMINOPLASTIA",
    "LIPOABDOMINOPLASTIA CON IGG": "LIPOABDOMINOPLASTIA",
    "LIPOABDOMINOPLASTIA VASER IGG": "LIPOABDOMINOPLASTIA COMPLEJA (VASER/IGG)",
    "LIPODISTROFIA ABDOMINOPLASTIA": "ABDOMINOPLASTIA",
    "LIPOSUCCION FULL TECH IGG": "LIPOSUCCIÓN COMPLEJA (VASER/IGG)",
    "LIPO FULL TECH IGG": "LIPOSUCCIÓN COMPLEJA (VASER/IGG)",
    "LIPOVASER IGG": "LIPOSUCCIÓN COMPLEJA (VASER/IGG)",
    "ENDOSCOPIA DIGESTIVA DILATACION": "ENDOSCOPIA DIGESTIVA",
    "ARTROTOMIA TEMPOROMANDIBULAR": "ARTROTOMÍA TEMPOROMANDIBULAR",
    "OSTEOSINTESIS COSTAL": "OSTEOSÍNTESIS COSTAL",
    "NEUMOPERITONEO": "LAPAROTOMÍA EXPLORADORA",
    "COLE LAP": "COLECISTECTOMÍA VLP",
    "HIPERTROFIA MAMARIA MAMOPLASTIA REDUCCION": "MAMOPLASTIA DE REDUCCIÓN",
    "RECONSTRUCCION CON EXPANSOR LIPOFILLING": "RECONSTRUCCIÓN MAMARIA CON EXPANSOR",
    "LEF CA MAMA RECONSTRUCCION PROTESIS": "RECONSTRUCCIÓN MAMARIA CON EXPANSOR",
    "AURICULO PLASTIA": "AURICULOPLASTIA",
    "AUMENTO MAMARIO LIPOSUCCION": "AUMENTO MAMARIO",
    "ESPERMATOCELECTOMIA": "ESPERMATOCELECTOMÍA",
    "HEMATOMA CERVICAL DRENAJE": "DRENAJE DE HEMATOMA",
    "HEMATOMA CERVICAL - DRENAJE": "DRENAJE DE HEMATOMA",

}



# EXPRESIONES REGULARES DE LIMPIEZA

_RE_PREFIJOS = re.compile(
    r"^\s*(?:SAP|PAD|LEF|HNP|ACHS\s*[-–]?\s*|GES\s*-?\s*|FNS\s*-?\s*)\s+",
    re.IGNORECASE,
)
_RE_SUFIJOS = re.compile(
    r"\s*(?:DERECHO|IZQUIERDO|DERECHA|IZQUIERDA|BILATERAL"
    r"|[LR]\d\-?[LS]\d?"            # vértebras tipo L4-S1
    r"|\([^)]*\)"                   # paréntesis finales, ej: (BANMEDICA)
    r"|\+?\s*OTS.*"                 # NUEVO: Corta todo lo que empiece con + OTS
    r"|\+?\s*RAFI.*"                # NUEVO: Corta todo lo que empiece con + RAFI
    r"|\+?\s*RED.*)\s*$",           # NUEVO: Corta todo lo que empiece con + RED
    re.IGNORECASE,
)
_RE_ESPACIOS = re.compile(r"\s+")

# NUEVO: Corta todo lo que venga después de un "LIO", "LIO OD" o "LIO OI" seguido de un signo "+"
_RE_LENTES = re.compile(r"(LIO\s*(?:OD|OI)?)\s*\+.*", re.IGNORECASE)


# DATACLASS RESULTADO

@dataclass(frozen=True)
class NormResult:
    canonical: str          # Nombre canónico final
    score: float            # Confianza 0–100 (100 = match exacto o alias)
    method: str             # "alias" | "exact" | "fuzzy" | "fallback"
    cleaned_input: str      # Input post-limpieza (para auditoría)



# CLASE PRINCIPAL

class NormalizadorIntervencion:
    """
    Normalizador de intervenciones quirúrgicas.

    Parameters
    ----------
    threshold : float
        Score mínimo para aceptar un match fuzzy (0–100). Default 80.
        Bajar a 75 aumenta cobertura pero arriesga falsos positivos.
        Subir a 88 reduce falsos positivos pero genera más "fallbacks".
    canonical_json : Path
        Ruta al JSON con la lista canónica. Default: canonical_interventions.json
        junto a este archivo.
    """

    def __init__(
        self,
        threshold: float = 80.0,
        canonical_json: Optional[Path] = None,
    ):
        self.threshold = threshold
        json_path = canonical_json or CANONICAL_JSON

        # Carga lista canónica desde JSON
        with open(json_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        self._canonicals: list[str] = data["categorias"]

        # Versiones sin tilde para comparación (paralela a _canonicals)
        self._canonicals_norm: list[str] = [
            self._quitar_tildes(c) for c in self._canonicals
        ]

        # Preparar MINI_ALIAS_MAP normalizado para matching exacto O(1)
        self._alias_map_norm: dict[str, str] = {
            self._quitar_tildes(k.upper()): v
            for k, v in MINI_ALIAS_MAP.items()
        }

        if _RAPIDFUZZ:
            # Pre-construir extractor rapidfuzz para mejor performance
            self._rf_choices = {
                self._quitar_tildes(c): c for c in self._canonicals
            }
        else:
            import warnings
            warnings.warn(
                "rapidfuzz no está instalado. Usando difflib como fallback. "
                "Instala rapidfuzz para mejor rendimiento: pip install rapidfuzz",
                ImportWarning,
                stacklevel=2,
            )

    
    # API PÚBLICA

    def normalizar(self, raw: str) -> NormResult:
        """
        Normaliza una intervención cruda y devuelve un NormResult con
        el canónico, el score de confianza y el método usado.

        Flujo:
          raw → pre_clean → MINI_ALIAS_MAP → fuzzy → fallback
        """
        if not raw or str(raw).strip() == "":
            return NormResult("SIN DATOS", 0.0, "fallback", "")

        cleaned = self._pre_clean(raw)

        if cleaned == "SIN DATOS":
            return NormResult("SIN DATOS", 0.0, "fallback", cleaned)

        cleaned_norm = self._quitar_tildes(cleaned)

        # Capa 2: MINI_ALIAS_MAP 
        if cleaned_norm in self._alias_map_norm:
            canonical = self._alias_map_norm[cleaned_norm]
            return NormResult(canonical, 100.0, "alias", cleaned)

        # Capa 3a: Exact match contra lista canónica 
        if cleaned_norm in self._canonicals_norm:
            idx = self._canonicals_norm.index(cleaned_norm)
            return NormResult(self._canonicals[idx], 100.0, "exact", cleaned)

        # Capa 3b: Fuzzy match 
        best_canonical, best_score = self._fuzzy_match(cleaned_norm)
        if best_score >= self.threshold:
            return NormResult(best_canonical, round(best_score, 1), "fuzzy", cleaned)

        # Capa 4: Fallback 
        # Si el fuzzy match fue < 80 y no está en el mini-mapa, lo marcamos para revisión.
        alerta = f"REQUIERE_REVISION: {cleaned}"
        return NormResult(alerta, 0.0, "fallback", cleaned)

    def normalizar_str(self, raw: str) -> str:
        """
        Drop-in replacement para normalizar_intervencion() del ETL original.
        Devuelve solo el nombre canónico (str).
        """
        return self.normalizar(raw).canonical

    def batch_normalizar(
        self, series, min_score_report: float = 0.0
    ) -> "pd.DataFrame":
        """
        Normaliza una pd.Series completa y devuelve un DataFrame con columnas:
          raw | cleaned_input | canonical | score | method
        """
        import pandas as pd

        results = [self.normalizar(v) for v in series]
        df = pd.DataFrame(
            {
                "raw": series.values,
                "cleaned_input": [r.cleaned_input for r in results],
                "canonical": [r.canonical for r in results],
                "score": [r.score for r in results],
                "method": [r.method for r in results],
            }
        )
        if min_score_report > 0:
            return df[df["score"] >= min_score_report]
        return df

    def reporte_cobertura(self, series) -> dict:
        """
        Devuelve un dict con estadísticas de cobertura para un conjunto de datos.
        Útil para validar el threshold y detectar gaps en la lista canónica.
        """
        results = [self.normalizar(v) for v in series]
        total = len(results)
        by_method = {}
        for r in results:
            by_method[r.method] = by_method.get(r.method, 0) + 1

        fallbacks = [r for r in results if r.method == "fallback"]
        fallback_freq: dict[str, int] = {}
        for r in fallbacks:
            fallback_freq[r.cleaned_input] = fallback_freq.get(r.cleaned_input, 0) + 1
        top_fallbacks = sorted(fallback_freq.items(), key=lambda x: -x[1])[:20]

        return {
            "total": total,
            "by_method": by_method,
            "coverage_pct": round((total - by_method.get("fallback", 0)) / total * 100, 1),
            "top_fallbacks": top_fallbacks,
            "threshold_usado": self.threshold,
            "backend": "rapidfuzz" if _RAPIDFUZZ else "difflib",
        }

    
    # MÉTODOS INTERNOS

    @staticmethod
    def _quitar_tildes(s: str) -> str:
        return "".join(
            c for c in unicodedata.normalize("NFD", s)
            if unicodedata.category(c) != "Mn"
        )

    @classmethod
    def _pre_clean(cls, raw: str) -> str:
        """
        Capa 1: limpieza estructural sin NINGÚN conocimiento de dominio.
        Solo elimina ruido que NO cambia el significado:
          - Prefijos de modalidad/financiamiento (PAD, LEF, ACHS, SAP...)
          - Sufijos de lateralidad (DERECHO, IZQUIERDO, BILATERAL)
          - Espacios múltiples
        """
        s = str(raw).strip().upper()
        # NUEVO: Amputar metadatos de los Lentes Intraoculares (LIO)
        # Transforma "LIO OI + 20.5 TECNIS..." en simplemente "LIO OI"
        s = _RE_LENTES.sub(r"\1", s).strip()
        s = _RE_ESPACIOS.sub(" ", s)

        # Eliminar prefijos en loop (puede haber más de uno: "PAD LEF ...")
        prev = None
        while prev != s:
            prev = s
            s = _RE_PREFIJOS.sub("", s).strip()

        # Eliminar sufijos de lateralidad
        s = _RE_SUFIJOS.sub("", s).strip()
        s = _RE_ESPACIOS.sub(" ", s)

        return s if s else "SIN DATOS"

    def _fuzzy_match(self, query_norm: str) -> tuple[str, float]:
        """
        Retorna (canonical, score) del mejor match.
        Usa rapidfuzz si está disponible, difflib como fallback.
        token_sort_ratio ignora el orden de las palabras:
          "RODILLA ARTROSCOPIA" == "ARTROSCOPIA RODILLA" → score 100
        """
        if _RAPIDFUZZ:
            result = rf_process.extractOne(
                query_norm,
                self._rf_choices.keys(),
                scorer=fuzz.token_sort_ratio,
            )
            if result is None:
                return "", 0.0
            best_norm_key, score, _ = result
            return self._rf_choices[best_norm_key], float(score)
        else:
            # difflib fallback: emula token_sort_ratio
            def _token_sort_ratio(a: str, b: str) -> float:
                a_s = " ".join(sorted(a.split()))
                b_s = " ".join(sorted(b.split()))
                return difflib.SequenceMatcher(None, a_s, b_s).ratio() * 100.0

            best_score, best_idx = 0.0, 0
            for i, cn in enumerate(self._canonicals_norm):
                score = _token_sort_ratio(query_norm, cn)
                if score > best_score:
                    best_score, best_idx = score, i
            return self._canonicals[best_idx], best_score



# COMPATIBILIDAD CON ETL ORIGINAL

# Instancia global con threshold default — para import directo como antes
_default_norm = NormalizadorIntervencion(threshold=80.0)


def normalizar_intervencion(raw: str) -> str:
    """
    Drop-in replacement para la función del mismo nombre en el ETL original.
    Retorna el nombre canónico como string.

    Ejemplo:
        # ETL original (500 líneas de ALIAS_MAP):
        df["Intervencion_Clean"] = df["Intervencion corta"].map(normalizar_intervencion)

        # Nuevo (sin cambiar esa línea):
        from normalizador_fuzzy import normalizar_intervencion
        df["Intervencion_Clean"] = df["Intervencion corta"].map(normalizar_intervencion)
    """
    return _default_norm.normalizar_str(raw)